# Generated by Django 4.2.25 on 2025-10-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('emissions', models.FloatField()),
                ('emission_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emissions',
                'ordering': ['year'],
            },
        ),
    ]
